---
title: "flat_model.Rmd empty"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# model

```{r function-model}
#' Mongoose model
#'
#' @param name Name of the model
#' @param properties List of properties
#' @param validator List of validators
#'
#' @export
model <- function(
  name,
  properties,
  validator
) {
  # Check that all properties are in the validator
  if (length(setdiff(names(properties), names(validator))) > 0) {
    stop("Some properties are not in the validator")
  }
  # Check that all validator are in the properties
  if (length(setdiff(names(validator), names(properties))) > 0) {
    stop("Some validator are not in the properties")
  }

  # This is a weird R6 class that is not really an R6 Class
  # Create an env that mimic self, private and public
  shelf <- new.env()

  shelf$object_con <- mongolite::mongo(
    db = con$db,
    collection = name,
    url = con$url,
    verbose = con$verbose,
    options = con$options
  )
  shelf$name <- name
  shelf$validator <- validator
  shelf$properties <- properties
  shelf$empt <- lapply(
    properties,
    function(x) x(1)
  )
  shelf$keys <- names(properties)

  cl <- R6::R6Class(
    "Mongoose",
    public = list(
      save = function(
  pagesize = 1000,
  stop_on_error = TRUE,
  ...
      ) {

        shelf$object_con$insert(
          data = private$props,
          pagesize = pagesize,
          stop_on_error = stop_on_error,
          ...
        )
      },
      initialize = function(
  props
 ) {
        check_props(props, shelf$validator)
        if (
          !all(names(props) %in% names(shelf$validator))
        ){
          stop(
            "[Undefined Prop] All props should be matched in the properties of the model"
          )
        }
        for (i in names(props)) {
          props[[i]] <- shelf$validator[[i]](
            props[[i]]
          )
        }
        private$props <- props
      }
    ),
    private = list(
      props = NULL
    )
  )
  cl$find <- function(
  query = list(),
  fields = '{}',
  sort = "{}",
  skip = 0,
  limit = 0,
  converter = jsonlite::toJSON
      ) {
    query <- converter(query)
    it <- shelf$object_con$iterate(
      query = query,
      fields = fields,
      sort = sort,
      skip = skip,
      limit = limit
    )
    res <- list()
    while (!is.null(batch <- it$one())) {
      tree <- list()
      for (k in shelf$keys) {
        tree[[k]] <- {
          if (is.null(batch[[k]])) {
            shelf$empt[[k]]
          } else {
            shelf$validator[[k]](batch[[k]])
          }
        }
      }
      res <- rlist::list.append(res, tree)
    }
    res
  }
  cl$find_one <- function(
    query = list(),
    fields = "{}",
    sort = "{}",
    skip = 0,
    limit = 0,
    converter = jsonlite::toJSON
  ) {
    query <- converter(query)
    it <- shelf$object_con$iterate(
      query = query,
      fields = fields,
      sort = sort,
      skip = skip,
      limit = limit
    )
    batch <- it$one()
    tree <- list()
    for (k in shelf$keys) {
      tree[[k]] <- {
        if (is.null(batch[[k]])) {
          shelf$empt[[k]]
        } else {
          shelf$validator[[k]](batch[[k]])
        }
      }
    }
    tree

  }
  cl$drop <- shelf$object_con$drop
  cl$count_documents <- shelf$object_con$count
  cl$disconnect <- shelf$object_con$disconnect
  cl
}

con <- new.env()

#' Connect Mongoose
#'
#' @inheritParams mongolite::mongo
#' @export
mongooser_connect <- function(
  db = "test",
  url = "mongodb://localhost",
  verbose = FALSE,
  options = mongolite::ssl_options()
) {
  # We don't actually connect but store the values
  con$db <- db
  con$url <- url
  con$verbose <- verbose
  con$options <- options
}

```

```{r examples-model}
# const mongoose = require('mongoose');
library(mongooser)
# mongoose.connect("mongodb://127.0.0.1:27017/test")
mongooser_connect(
  db = "test",
  url = "mongodb://localhost",
  verbose = FALSE,
  options = mongolite::ssl_options()
)

# const Cat = mongoose.model('Cat', { name: String });
Cat <- model(
  "Cat",
  properties = list(
    name = character,
    age = numeric
  ),
  validator = list(
    name = as.character,
    age = as.numeric
  )
)
Cat$drop()

# const kitty = new Cat({ name: 'Zildjian' });
kitty <- Cat$new(
  list(
    name = "Zildjian",
    age = 12
  )
)
# const kitty = new Cat({ name: 'Zildjian' });
fluffy <- Cat$new(
  list(
    name = "fluffy"
  )
)

# kitty.save().then(() => console.log('meow'));
kitty$save()
fluffy$save()

Cat$find()

Cat$find_one()
Cat$find_one(list(name = "fluffy"))

Cat$drop()
Cat$disconnect()
Cat$count_documents()

Food <- model(
  "Food",
  properties = list(
    ingredient = character,
    sticker = character,
    to_reheat = logical
  ),
  validator = list(
    ingredient = as.character,
    sticker = as.character,
    to_reheat = as.logical
  )
)
Food$drop()
f_m <- list(
  ingredient = "carrot",
  sticker = "carrot",
  to_reheat = TRUE
)
monday <- Food$new(
  f_m
)
monday$save()
res <- Food$find()[[1]]
class(res$day) == class(f_m$day)


f_t <- list(
  ingredient = c("carrot", "potato"),
  sticker = "carrot",
  to_reheat = 1
)
tuesday <- Food$new(
  f_t
)
tuesday$save()
Food$find()[[2]]$day
class(Food$find()[[2]]$to_reheat)

Food$find(
  list(
    sticker = "carrot"
  )
)
```


```{r tests-model}
test_that("model works", {
  skip_on_ci()
  skip_on_cran()
  skip_if(
    attempt::is_try_error(
      attempt::attempt({
        mongolite::mongo()$find()
      }, silent = TRUE)
    )
  )
  mongooser_connect(
    db = "test",
    url = "mongodb://localhost",
    verbose = FALSE,
    options = mongolite::ssl_options()
  )
  # const Cat = mongoose.model('Cat', { name: String });
  Cat <- model(
    "Cat",
    properties = list(
      name = character,
      age = numeric
    ),
    validator = list(
      name = as.character,
      age = as.numeric
    )

  )
  expect_true(
    inherits(Cat, "R6ClassGenerator")
  )
  expect_true(
    "find" %in% names(Cat)
  )
  Cat$drop()

  # const kitty = new Cat({ name: 'Zildjian' });
  kitty <- Cat$new(
    list(
      name = "Zildjian",
      age = 12
    )
  )
  expect_true(
    inherits(kitty, "Mongoose")
  )
  expect_true(
    "save" %in% names(kitty)
  )

  # kitty.save().then(() => console.log('meow'));
  kitty$save()
  expect_equal(
    Cat$find()[[1]]$name,
    "Zildjian"
  )
  expect_equal(
    Cat$find()[[1]]$age,
    12
  )
})
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
rm(list = ls())
fusen::inflate(
  flat_file = "dev/flat_model.Rmd",
  vignette_name = NA
)
grkstyle::grk_style_pkg()
```

