# WARNING - Generated by {fusen} from dev/flat_model.Rmd: do not edit by hand

test_that("model works", {
  skip_on_ci()
  skip_on_cran()
  skip_if(
    attempt::is_try_error(
      attempt::attempt(
        {
          mongolite::mongo()$find()
        },
        silent = TRUE
      )
    )
  )
  mongooser_connect(
    db = "test",
    url = "mongodb://localhost",
    verbose = FALSE,
    options = mongolite::ssl_options()
  )
  # const Cat = mongoose.model('Cat', { name: String });
  Cat <- model(
    "Cat",
    properties = list(
      name = character,
      age = numeric
    ),
    validator = list(
      name = as.character,
      age = as.numeric
    )
  )
  expect_true(
    inherits(Cat, "R6ClassGenerator")
  )
  expect_true(
    "find" %in% names(Cat)
  )
  Cat$drop()

  # const kitty = new Cat({ name: 'Zildjian' });
  kitty <- Cat$new(
    list(
      name = "Zildjian",
      age = 12
    )
  )
  expect_true(
    inherits(kitty, "Mongoose")
  )
  expect_true(
    "save" %in% names(kitty)
  )

  # kitty.save().then(() => console.log('meow'));
  kitty$save()
  expect_equal(
    Cat$find()[[1]]$name,
    "Zildjian"
  )
  expect_equal(
    Cat$find()[[1]]$age,
    12
  )
})
