# WARNING - Generated by {fusen} from dev/flat_draft.Rmd: do not edit by hand

test_that("check works", {
  expect_error(
    check_props(
      properties = list(
        name = "Zildjian"
      ),
      validator = list(
        age = as.numeric
      )
    )
  )
  expect_error(
    check_vals(
      properties = list(
        name = "Zildjian"
      ),
      validator = list(
        name = as.character,
        age = as.numeric
      )
    )
  )
})
