# WARNING - Generated by {fusen} from dev/flat_draft.Rmd: do not edit by hand

#' Title
#'
#' Description
#'
#' @return
#'
#' @noRd
#' @examples
#' check_props(
#'   properties = list(
#'     name = "Zildjian"
#'   ),
#'   validator = list(
#'     name = as.character
#'   )
#' )
#' check_vals(
#'   properties = list(
#'     name = "Zildjian"
#'   ),
#'   validator = list(
#'     name = as.character
#'   )
#' )
check_props <- function(
  properties,
  validator
) {
  all_nms <- all(
    names(properties) %in% names(validator)
  )
  if (!all_nms) {
    stop(
      "[Undefined Entry] All properties should be matched in the validator",
      call. = FALSE
    )
  }
}

check_vals <- function(
  properties,
  validator
) {
  all_nms <- all(
    names(validator) %in% names(properties)
  )
  if (!all_nms) {
    stop(
      "[Undefined Entry] All validator should be matched in the properties",
      call. = FALSE
    )
  }
}
