# WARNING - Generated by {fusen} from dev/flat_model.Rmd: do not edit by hand

#' Mongoose model
#'
#' @param name Name of the model
#' @param properties List of properties
#' @param validator List of validators
#'
#' @export
#' @examples
#' # const mongoose = require('mongoose');
#' library(mongooser)
#' 
#' # mongoose.connect("mongodb://127.0.0.1:27017/test")
#' mongooser_connect(
#'   db = "test",
#'   url = "mongodb://localhost",
#'   verbose = FALSE,
#'   options = mongolite::ssl_options()
#' )
#' 
#' # const Cat = mongoose.model('Cat', { name: String });
#' Cat <- model(
#'   "Cat",
#'   properties = list(
#'     name = character,
#'     age = numeric
#'   ),
#'   validator = list(
#'     name = as.character,
#'     age = as.numeric
#'   )
#' )
#' Cat$drop()
#' 
#' # const kitty = new Cat({ name: 'Zildjian' });
#' kitty <- Cat$new(
#'   list(
#'     name = "Zildjian",
#'     age = 12
#'   )
#' )
#' # const kitty = new Cat({ name: 'Zildjian' });
#' fluffy <- Cat$new(
#'   list(
#'     name = "fluffy"
#'   )
#' )
#' 
#' # kitty.save().then(() => console.log('meow'));
#' kitty$save()
#' fluffy$save()
#' 
#' Cat$find()
#' 
#' Cat$drop()
#' 
#' Food <- model(
#'   "Food",
#'   properties = list(
#'     ingredient = character,
#'     sticker = character,
#'     to_reheat = logical
#'   ),
#'   validator = list(
#'     ingredient = as.character,
#'     sticker = as.character,
#'     to_reheat = as.logical
#'   )
#' )
#' Food$drop()
#' f_m <- list(
#'   ingredient = "carrot",
#'   sticker = "carrot",
#'   to_reheat = TRUE
#' )
#' monday <- Food$new(
#'   f_m
#' )
#' monday$save()
#' res <- Food$find()[[1]]
#' class(res$day) == class(f_m$day)
#' 
#' 
#' f_t <- list(
#'   ingredient = c("carrot", "potato"),
#'   sticker = "carrot",
#'   to_reheat = 1
#' )
#' tuesday <- Food$new(
#'   f_t
#' )
#' tuesday$save()
#' Food$find()[[2]]$day
#' class(Food$find()[[2]]$to_reheat)
#' 
#' Food$find(
#'   list(
#'     sticker = "carrot"
#'   )
#' )
model <- function(
  name,
  properties,
  validator
) {
  # Check that all properties are in the validator
  if (length(setdiff(names(properties), names(validator))) > 0) {
    stop("Some properties are not in the validator")
  }
  # Check that all validator are in the properties
  if (length(setdiff(names(validator), names(properties))) > 0) {
    stop("Some validator are not in the properties")
  }

  object_con <- mongolite::mongo(
    db = con$db,
    collection = name,
    url = con$url,
    verbose = con$verbose,
    options = con$options
  )

  cl <- R6::R6Class(
    "Mongoose",
    public = list(
      save = function(
  pagesize = 1000,
  stop_on_error = TRUE,
  ...
      ) {
        object_con$insert(
          data = private$properties,
          pagesize = pagesize,
          stop_on_error = stop_on_error,
          ...
        )
      },
      initialize = function(
  properties
 ) {
        check_props(properties, validator)
        for (i in names(properties)) {
          properties[[i]] <- validator[[i]](
            properties[[i]]
          )
        }
        private$properties <- properties
      }
    ),
    private = list(
      validator = validator,
      properties = NULL
    )
  )
  cl$find <- function(
  query = list(),
  fields = '{"_id" : 0}',
  sort = "{}",
  skip = 0,
  limit = 0,
  converter = jsonlite::toJSON
      ) {
    query <- converter(query)
    it <- object_con$iterate(
      query = query,
      fields = fields,
      sort = sort,
      skip = skip,
      limit = limit
    )
    empt <- lapply(
      properties,
      \(x) x(1)
    )
    res <- list()
    keys <- names(properties)
    while (!is.null(batch <- it$one())) {
      tree <- list()
      for (k in keys) {
        tree[[k]] <- {
          if (is.null(batch[[k]])) {
            empt[[k]]
          } else {
            validator[[k]](batch[[k]])
          }
        }
      }
      res <- rlist::list.append(res, tree)
    }
    res
  }
  cl$drop <- function() {
    object_con$drop()
  }
  cl
}
con <- new.env()

#' Connect Mongoose
#'
#' @inheritParams mongolite::mongo
#' @export
mongooser_connect <- function(
  db = "test",
  url = "mongodb://localhost",
  verbose = FALSE,
  options = mongolite::ssl_options()
) {
  # We don't actually connect but store the values
  con$db <- db
  con$url <- url
  con$verbose <- verbose
  con$options <- options
}

